name: Package Release

on:
  push:
    branches:
      - main
      - development

jobs:
  release:
    name: Generate release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'

      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm ci

      - name: Release development version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: npx semantic-release
